### ISSUE TITLE
定义User对象

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/Triclops#1]
# 定义User对象

+ User对象包括以下属性 name(唯一,不能使用怪异字符) gender性别(可选填) nick(显示给其它人看的名称) phone(手机号码,用于重置密码)
+ User对象定义在文件 [User.java](https://github.com/HP-Enterprise/Triclops/blob/dev/src/main/java/com/hp/triclops/User.java) 中
+ 定义表名称

**Comment by AceBear** [comment]
@jiangli0509 2点需要注意
1. 从dev分支分出你自己的工作分支进行工作
2. User不要包含密码,密码由另外的类来承担

**Comment by jiangli0509** [comment]
已合并到dev分支

**Comment by AceBear** [comment]
1. SQL脚本手写,不要用工具生成
2. 用UTF8编码

**Comment by jiangli0509** [comment]
已完成，提交到dev了。

**Comment by AceBear** [comment]
Id列上需要增加下面的标注
```java
@GeneratedValue(strategy = GenerationType.IDENTITY)
```
SQL脚本上也需要为ID列设置IDENTITY
