### ISSUE TITLE
实体类的生成

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/Triclops#4]
# 实体类的生成

1. 我们应该用某种工具来从数据库生成对应的实体类
2. 这种工具不应依赖于任何一种开发IDE(IDEA 或 Eclipse)
3. 生成过程可以被gradle集成

**Comment by AceBear** [comment]
参考
http://openjpa.apache.org/builds/2.4.0/apache-openjpa/docs/ref_guide_pc_reverse.html

**Comment by jefferyxq** [comment]
目前在数据库中已有相应的表结构，以及表与表之间的关联，在生成实体类的时候，注意也要将表与表中的关系提现出来，如one to many等等。

**Comment by jack-luj** [comment]
目前已经实现一个初步可用版本，存在的问题是我在本地新建了一个Idea Java项目做的，代码提交该如何处理？我先加到Triclops还是其他办法？ @jefferyxq   @AceBear
