### ISSUE TITLE
关于settings.gradle

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/Triclops#5]
settings.gradle 不要加入.gitignore文件中
这个文件在gradle中有其它重要的作用

原因看下面的链接
[https://docs.gradle.org/current/userguide/build_lifecycle.html#sec:multi_project_builds](https://docs.gradle.org/current/userguide/build_lifecycle.html#sec:multi_project_builds)

对于Triclops项目,这个文件应该被删除,而不是加入到.gitignore中

**Comment by lahmyyc** [comment]
已修改
