### ISSUE TITLE
Application.java里的代码是有目的的

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/Triclops#7]
在Application.java里有下面这样一节代码,这节代码是有用途的
```
for(User user : userRepository.findAll()){
          System.out.println(user);
      }
```

Triclops.jar被配置为可以单独运行,这样当执行java Triclopse.jar时,如果一切正常,就会打印所有用户出来,这样就可以确认Triclopse是正常的.

**所以,不要随意删除他人的代码**

如果有不同看法,请发起一个issue把问题单独提出来

或者如果有更好办法,也可以直接开一个分支,把代码写好,然后发起一个PULL-Request给我们的集成分支dev ,我们再来确认是否合并入dev分支中.

**Comment by lahmyyc** [comment]
已补全
