### ISSUE TITLE
UserService

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/Triclops#8]
去除UserService & UserServiceImpl

因为 UserRepository已经包含了它的所有功能, UserRepository派生自CrudRepository, 而CrudRepository已经实现了诸如findAll, findById这样的方法

另外, User的管理这项工作是分派给 @jiangli0509 完成的
因此 ** 请不要额外做没有分派给自己工作 **

**如果有更好的想法,可以单独开一个issue**
**也欢迎单独开一个分支,然后发起一个PULL-REQUEST**

**Comment by lahmyyc** [comment]
经讨论，业务层是必须的，所有操作都应该通过业务层来访问数据层
